### PR TITLE
Add verbose flag to debug deploy

### PR DESCRIPTION
**Pull request by zephraph**
Enables verbose mode to see what the deployment output is. I'm specifically setting this as a patch to try to force a new deploy.

### CODE REVIEW

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v6.0.0 :rocket:

**Pull request merged**
