### PR TITLE
Don't deploy trivial changes

### PR DESCRIPTION
**Pull request by zephraph**
Added trivial to be an internal change, but that seemed to still be deploying. Now it's not.

### CODE REVIEW

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v6.0.0 :rocket:

**Pull request merged**
