### PR TITLE
Use arsty shared auto config

### PR DESCRIPTION
**Pull request by just-be-dev**
🐱

### CODE REVIEW

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v6.0.0 :rocket:

**Pull request merged**
