### PR TITLE
Make trivial considered an internal change

### PR DESCRIPTION
**Pull request by zephraph**
The idea is to have changes marked as trivial still show up in the changelog.

### CODE REVIEW

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v6.0.0 :rocket:

**Pull request merged**
