### PR TITLE
Bump to styled-components@4.0.3

### PR DESCRIPTION
**Pull request by damassi**
Bump to match the rest of our apps.

### CODE REVIEW

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by zephraph** [comment]
:rocket: PR was released in v5.0.0 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v6.0.0 :rocket:

**Pull request merged**
